apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2025-07-15T19:29:36Z"
  labels:
    istio-injection: enabled
    kubernetes.io/metadata.name: beta
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:kubernetes.io/metadata.name: {}
    manager: kubectl-create
    operation: Update
    time: "2025-07-15T19:29:36Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          f:istio-injection: {}
    manager: kubectl-label
    operation: Update
    time: "2025-07-15T19:29:36Z"
  name: beta
  resourceVersion: "1688"
  uid: 77540dd6-5310-4053-a21f-0b9b57bee390
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
