---
dependency:
  name: galaxy
platforms:
- name: default
  groups:
  - k8s
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: junit
  playbooks:
    destroy: ../default/destroy.yml
    prepare: ../default/prepare.yml
  inventory:
    group_vars:
      all:
        kiali_operator_assets_path : "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/deploy"
        cr_file_path: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/molecule/kiali-cr.yaml"
        istio:
          control_plane_namespace: istio-system
        kiali:
          accessible_namespaces:
          - "**"
          operator_namespace: kiali-operator
          operator_image_name: quay.io/kiali/kiali-operator
          operator_version: latest
          operator_watch_namespace: ""
          operator_clusterrolebindings: "- clusterrolebindings"
          operator_clusterroles: "- clusterroles"
          auth_strategy: openshift
          image_name: quay.io/kiali/kiali
          label_selector: ""
          image_version: latest
          # Because when the version is set to Latest, it needs to be Always
          image_pull_policy: Always
scenario:
  name: default
  test_sequence:
  - prepare
  - converge
  - destroy
