// This file is auto-generated by scripts/generateChatbotConversations.js. Do not edit manually.
import actionCreateIstioObject from './conversations/actionCreateIstioObject.json';
import actionMeshGraph from './conversations/actionMeshGraph.json';
import actionNavigationBookinfoGraph from './conversations/actionNavigationBookinfoGraph.json';
import actionNavigationLogsReviews_v2 from './conversations/actionNavigationLogsReviews-v2.json';
import actionNavigationMeshGraph from './conversations/actionNavigationMeshGraph.json';
import actionNavigationMetricsReviews_v2 from './conversations/actionNavigationMetricsReviews-v2.json';
import analyzeOverview from './conversations/analyzeOverview.json';
import citationsTrafficShifting from './conversations/citationsTrafficShifting.json';
import citationsWorkloads from './conversations/citationsWorkloads.json';
import talkCheckMyMesh from './conversations/talkCheckMyMesh.json';
import talkGraphEmpty from './conversations/talkGraphEmpty.json';
import talkIstioTrafficShifting from './conversations/talkIstioTrafficShifting.json';

export const conversationModuleEntries: Array<[string, unknown]> = [
  ['actionCreateIstioObject', actionCreateIstioObject],
  ['actionMeshGraph', actionMeshGraph],
  ['actionNavigationBookinfoGraph', actionNavigationBookinfoGraph],
  ['actionNavigationLogsReviews-v2', actionNavigationLogsReviews_v2],
  ['actionNavigationMeshGraph', actionNavigationMeshGraph],
  ['actionNavigationMetricsReviews-v2', actionNavigationMetricsReviews_v2],
  ['analyzeOverview', analyzeOverview],
  ['citationsTrafficShifting', citationsTrafficShifting],
  ['citationsWorkloads', citationsWorkloads],
  ['talkCheckMyMesh', talkCheckMyMesh],
  ['talkGraphEmpty', talkGraphEmpty],
  ['talkIstioTrafficShifting', talkIstioTrafficShifting]
];
