# creates service account with permissions to access prometheus metrics
kind: ServiceAccount
apiVersion: v1
metadata:
  name: ${MCP}-mcp-server
  namespace: ${MCP_NAMESPACE}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ${MCP}-mcp-server:system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: ${MCP}-mcp-server
    namespace: ${MCP_NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ${MCP}-mcp-server
rules:
- apiGroups:
  - "config.openshift.io"
  resources:
  - consoles
  verbs:
  - get
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ${MCP}-mcp-server
subjects:
  - kind: ServiceAccount
    name: ${MCP}-mcp-server
    namespace: ${MCP_NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ${MCP}-mcp-server
