- name: Get cluster roles
  k8s_info:
   api_version: rbac.authorization.k8s.io/v1
   kind: ClusterRole
   name: kiali-viewer
  register: clusterroles

- name: Assert that cluster roles exist
  assert:
    that: "{{ clusterroles.resources | length == 1 }}"
    fail_msg: "The kiali-viewer cluster role does not exist"

- name: Get cluster role binding
  k8s_info:
   api_version: rbac.authorization.k8s.io/v1
   kind: ClusterRoleBinding
   name: kiali
  register: clusterrolebindings

- name: Assert the cluster role binding provides the read-only viewer role
  assert:
    that:
    - "{{ clusterrolebindings.resources[0] | default({}) | json_query('roleRef.name') == 'kiali-viewer' }}"
    fail_msg: "The kiali cluster role binding did not have the read-only roleref 'kiali-viewer'"
