= Releasing Kiali

Kiali is released using a Jenkins Pipeline. If you need to release
a new version of Kiali, please ask to a member of the QE team to
trigger the release for you. Alternatively, ask the QE team for
access to the Jenkins instance and trigger the release by yourself.

Currently, the Pipeline supports only minor releases and will release the
back-end and the front-end together. If you need to do a patch or a major
release, you'll need to <<run-locally,run the release process locally
in your machine>>.

Edge-snapshots (or snapshots after merged PRs) are handled by Travis.

== Finished product

When the release process is complete, a new DockerHub image will be available in the
link:https://hub.docker.com/r/kiali/kiali/tags/[Kiali Docker Hub repo].

== Actions before creating a release

These actions are not performed by the release process. Please, do
these actions manually before running the release process.

=== Creating a new JIRA issue

If you know that you'll spend a considerable amount of time doing
the release, create a new issue on
link:https://issues.jboss.org/browse/KIALI[JIRA] detailing the
release, and add sub-tasks if necessary.

=== Updating Docs

Make sure that the https://www.kiali.io/gettingstarted/[_Getting Started_ document]
of the website is up to date and works with the new version.

The doc sources are in the link:https://github.com/kiali/kiali.io[kiali/kiali.io repository].
Update the document, and create a PR.

== Actions after creating a release

These actions are not performed by the release process. Please, do
these actions manually after the release process finishes successfully.

=== Updating JIRA issues

Edit all issues in `Ready to Release` state with `Fix-Version`:

* Use this query https://issues.jboss.org/issues/?filter=12336798
* Use Tools>Bulk Change>All XX issue(s)
* Select all issues and press `Next`
* `Edit issues`
* `Change Fix Version/s`>`Add to existing`>Pick the version to release>Unselect `Send mail for this update`>Next>Confirm

Transition all issues to `Released`:

* Use this query https://issues.jboss.org/issues/?filter=12337486
* Use Tools>Bulk Change>All XX issue(s)
* Select all issues and press `Next`
* `Transition issues`
* `Released`>Next
* Unselect `Send mail for this update`>Next>Confirm

After that, close the release issues, and then, create a new `Release` in JIRA
for the next release.

Mark the current version as released, and create a new minor version:
https://issues.jboss.org/projects/KIALI?selectedItem=com.atlassian.jira.jira-projects-plugin:release-page

=== Notify Istio and Openshift Istio Teams for changes

There are no fixed steps for releasing a new version on the Istio installer,
each release is kind of different.

This has been done a few times before, so they can be used as references:

* https://github.com/istio/istio/pull/5869
* https://github.com/istio/istio/pull/5921
* https://github.com/istio/istio/pull/6192
* https://github.com/istio/istio/pull/6592
* https://github.com/istio/istio/pull/6594
* https://github.com/istio/istio/pull/7042
* https://github.com/istio/istio/pull/7007

Those PRs cover both the ansible-installer and the helm installer updates.

=== Send out notifications

Finally, we just need to send the nofications to create awareness of the new
release.

Post an email about the release on our
link:https://groups.google.com/forum/#!search/kiali-dev[Mailing List].

Send a message on our channel at Freenode, #kiali.

Post a message on our twitter,
link:https://www.twitter.com/KialiProject[@KialiProject]. If you don't know
who's responsible for the account, ask on IRC.

== Release process of the Jenkins Pipeline

The Pipeline uses the Jenkinsfile located at
link:deploy/jenkins-ci/Jenkinsfile[deploy/jenkins-ci/Jenkinsfile]
in the https://github.com/kiali/kiali/[kiali/kiali] repository.

The Pipeline performs the following actions to do the release:

* Checkouts the code of, both, the back-end and the front-end
* Builds the back-end and the front-end
* Run tests for back-end and front-end
* If all tests pass:
** The front-end is released to NPM
** A docker image integrating the back-end and the front-end is built
   and pushed to DockerHub
** Tags for the new releases are created
** Minor version branches are created named of the form _vX.Y_ 
** PRs are created to prepare _master_ branches for the next version

== [[run-locally]]Running the release process locally

If you don't have access to the Jenkins instance or the release process
through Jenkins doesn't suit your needs, you may want to run the release
process _locally_.

=== Requirements

You must have write permissions to the https://github.com/kiali/kiali[kiali public GitHub repository] in
order to be able to push the tags. You will also need an DockerHub account that
is able to publish to the
https://hub.docker.com/r/kiali/kiali/[DockerHub kiali/kiali repository].

You will need a working dev environment (git, golang, docker, make, etc).
You will also need the following tools available in your $PATH:

* https://github.com/fsaintjacques/semver-tool[semver] shell utility - used
  to update version numbers
* https://www.npmjs.com/[npm] - to download and package kiali-ui
* curl - because the release process places PRs using the GitHub API

If you want the release process to push a PR for you to prepare the code for
the next release, you will need a GitHub Token for your account.

It's assumed that you are running the release process in you fork of the
https://github.com/kiali/kiali[kiali/kiali GitHub repository].

=== Making the release

. Make a release of the front-end, if needed
** Please, follow the https://github.com/kiali/kiali-ui/blob/master/RELEASING.adoc[releasing guide for the front-end]
** You can omit this step if there is no need to release the front-end. Kiali
   will be released using the latest version of the front-end.
. Login to DockerHub
** `docker login docker.io`
. Checkout the code that you want to release:
** `git checkout branch_to_release` (usually, you should release "master")
** Be advised that the release process will commit changes locally
. The version that is specified in `VERSION` variable of the main Makefile
  is what will be used for the release. If needed, modify the version numbers. The
  `-SNAPSHOT` fragment will be removed.
. If you want the release process to create a PR for you, to prepare the code for
  the next version:
** `export GH_TOKEN={your_github_token}`
** A branch is always created in your fork of the code. So, if you don’t have a
   token, you can place the PR manually.
. Run the release process:
** `CONSOLE_VERSION="{ui-version}" make -f deploy/jenkins-ci/Makefile release`

In the last step, you can omit the CONSOLE_VERSION variable. However, it is
_**very** highly_ recommended that you specify the version of the UI to package.
If you released kiali-ui (step 1), you should specify the version you just released.
Else, you should specify whatever version you need packaged. If you don't specify
a kiali-ui version, the latest version that was published in NPM will be used, which is not necessarily the latest _released_ version (most likely it will be a snapshot).

=== Available options

* The generated Docker image is published to kiali/kiali DockerHub repository.
  If you want to publish to another repository:
** `DOCKER_NAME="{repository}" make -f deploy/jenkins-ci/Makefile release``
* It's assumed that you are doing a major or a minor release. So, a new version
  branch is created in the kiali repository (the branch name is like
  "vMAJOR.MINOR"). You can omit the creation of this branch:
** `OMIT_VERSION_BRANCH=y make -f deploy/jenkins-ci/Makefile release`
* The release process bumps the minor part of the version specified in
  the Makefile. If this doesn't meet your needs, you can specify what will be the 
  next version, so that the PR is created correctly:
** `BACKEND_BUMPED_VERSION="major.minor.patch" make -f deploy/jenkins-ci/Makefile release`
* The release process always creates a branch in your repository with the
  required changes to prepare the code for the next release. By default, the name
  of the branch is _prepare_next_version_. If you want to customize the name of
  the branch:
** `BUMP_BRANCH_ID={branch_name} make -f deploy/jenkins-ci/Makefile release`
