import * as React from 'react';
import { connect } from 'react-redux';
import {
  Card,
  CardBody,
  CardHeader,
  DescriptionList,
  DescriptionListDescription,
  DescriptionListGroup,
  DescriptionListTerm,
  Grid,
  GridItem,
  Stack,
  StackItem,
  Title,
  TitleSizes
} from '@patternfly/react-core';
import { ServiceId, ServiceDetailsInfo, WorkloadOverview } from '../../types/ServiceInfo';
import { AppWorkload } from '../../types/App';
import { Spire } from '../../components/Spire/Spire';
import {
  DestinationRuleC,
  filterAutogeneratedGateways,
  Gateway,
  getGatewaysAsList,
  getK8sGatewaysAsList,
  K8sGateway,
  ObjectValidation,
  PeerAuthentication,
  Validations
} from '../../types/IstioObjects';
import { detailGridStyle, detailLeftColumnStyle, flexFillStyle } from 'styles/FlexStyles';
import { PromisesRegistry } from 'utils/CancelablePromises';
import { DurationInSeconds } from 'types/Common';
import { GraphDataSource } from 'services/GraphDataSource';
import {
  drToIstioItems,
  vsToIstioItems,
  gwToIstioItems,
  seToIstioItems,
  k8sHTTPRouteToIstioItems,
  k8sGRPCRouteToIstioItems,
  validationKey,
  k8sGwToIstioItems,
  k8sInferencePoolToIstioItems
} from '../../types/IstioConfigList';
import { canCreate, canUpdate } from '../../types/Permissions';
import { KialiAppState } from '../../store/Store';
import { durationSelector } from '../../store/Selectors';
import { ServiceNetwork } from './ServiceNetwork';
import { IstioConfigCard } from '../../components/IstioConfigCard/IstioConfigCard';
import { ServiceWizard } from '../../components/IstioWizards/ServiceWizard';
import { ConfirmDeleteTrafficRoutingModal } from '../../components/IstioWizards/ConfirmDeleteTrafficRoutingModal';
import { WizardAction, WizardMode } from '../../components/IstioWizards/WizardActions';
import { deleteServiceTrafficRouting } from '../../services/Api';
import { addError, addSuccess } from '../../utils/AlertUtils';
import { triggerRefresh } from '../../hooks/refresh';
import { serverConfig } from 'config';
import { MiniGraphCard } from 'pages/Graph/MiniGraphCard';
import { HealthStatusPopover } from '../../components/Health/HealthStatusPopover';
import { LocalTime } from '../../components/Time/LocalTime';
import { TextOrLink } from '../../components/Link/TextOrLink';
import { renderAPILogo } from '../../components/Logo/Logos';
import { AmbientLabel, tooltipMsgType } from '../../components/Ambient/AmbientLabel';
import { DetailDescription } from '../../components/DetailDescription/DetailDescription';
import { EditableAnnotationsCard } from '../../components/Label/EditableAnnotationsCard';
import { EditableLabelsCard } from '../../components/Label/EditableLabelsCard';
import { Labels } from '../../components/Label/Labels';
import { getIstioObjectGVK } from '../../utils/IstioConfigUtils';
import { getAppLabelName } from 'config/ServerConfig';
import { Paths } from '../../config';
import { navigateToFilteredList } from '../PageUtils';
import { t } from 'utils/I18nUtils';

type ReduxProps = {
  duration: DurationInSeconds;
};

interface Props extends ServiceId, ReduxProps {
  cluster?: string;
  duration: DurationInSeconds;
  gateways: Gateway[];
  k8sGateways: K8sGateway[];
  onSaveAnnotations: (annotations: Record<string, string>) => void;
  onSaveLabels: (labels: Record<string, string>) => void;
  peerAuthentications: PeerAuthentication[];
  serviceDetails?: ServiceDetailsInfo;
  validations: Validations;
}

type ServiceInfoState = {
  showConfirmDeleteTrafficRouting: boolean;
  showWizard: boolean;
  updateMode: boolean;
  wizardType: string;
};

class ServiceInfoComponent extends React.Component<Props, ServiceInfoState> {
  private promises = new PromisesRegistry();
  private graphDataSource = new GraphDataSource();

  constructor(props: Props) {
    super(props);
    this.state = {
      showWizard: false,
      wizardType: '',
      updateMode: false,
      showConfirmDeleteTrafficRouting: false
    };
  }

  componentDidMount(): void {
    this.fetchBackend();
  }

  componentDidUpdate(prev: Props): void {
    if (prev.duration !== this.props.duration || prev.serviceDetails !== this.props.serviceDetails) {
      this.fetchBackend();
    }
  }

  private fetchBackend = (): void => {
    if (!this.props.serviceDetails) {
      return;
    }

    this.promises.cancelAll();
    this.graphDataSource.fetchForService(
      this.props.duration,
      this.props.namespace,
      this.props.service,
      this.props.cluster
    );
  };

  private getServiceValidation(): ObjectValidation | undefined {
    if (this.props.validations && this.props.validations.service && this.props.serviceDetails) {
      return this.props.validations.service[
        validationKey(this.props.serviceDetails.service.name, this.props.namespace)
      ];
    }

    return undefined;
  }

  private handleWizardClose = (changed: boolean): void => {
    this.setState({
      showWizard: false
    });

    if (changed) {
      triggerRefresh();
    }
  };

  private handleConfirmDeleteServiceTrafficRouting = (): void => {
    this.setState({
      showConfirmDeleteTrafficRouting: false
    });

    deleteServiceTrafficRouting(this.props.serviceDetails!)
      .then(_results => {
        addSuccess(`Istio Config deleted for ${this.props.serviceDetails?.service.name} service.`);

        triggerRefresh();
      })
      .catch(error => {
        addError('Could not delete Istio config objects.', error);
      });
  };

  private handleDeleteTrafficRouting = (_key: string): void => {
    this.setState({ showConfirmDeleteTrafficRouting: true });
  };

  private handleLaunchWizard = (action: WizardAction, mode: WizardMode): void => {
    this.setState({
      showWizard: true,
      wizardType: action,
      updateMode: mode === 'update'
    });
  };

  private renderDetailsCard(): React.ReactNode {
    const sd = this.props.serviceDetails;
    if (!sd) {
      return null;
    }

    const service = sd.service;
    let serviceType = t('Service');
    if (service.type === 'External') {
      serviceType = t('External Service');
    }

    return (
      <StackItem key="details">
        <Card data-test="service-details-card" isCompact>
          <CardBody>
            <DescriptionList columnModifier={{ default: '2Col' }} isCompact>
              {service.cluster && (
                <DescriptionListGroup data-test="details-cluster">
                  <DescriptionListTerm>{t('Cluster')}</DescriptionListTerm>
                  <DescriptionListDescription>{service.cluster}</DescriptionListDescription>
                </DescriptionListGroup>
              )}

              <DescriptionListGroup data-test="details-status">
                <DescriptionListTerm>{t('Status')}</DescriptionListTerm>
                <DescriptionListDescription>
                  <HealthStatusPopover health={sd.health} />
                </DescriptionListDescription>
              </DescriptionListGroup>

              <DescriptionListGroup data-test="details-created">
                <DescriptionListTerm>{t('Created')}</DescriptionListTerm>
                <DescriptionListDescription>
                  <LocalTime time={service.createdAt} />
                </DescriptionListDescription>
              </DescriptionListGroup>

              <DescriptionListGroup data-test="details-type">
                <DescriptionListTerm>{t('Type')}</DescriptionListTerm>
                <DescriptionListDescription>{serviceType}</DescriptionListDescription>
              </DescriptionListGroup>

              <DescriptionListGroup data-test="details-version">
                <DescriptionListTerm>{t('Version')}</DescriptionListTerm>
                <DescriptionListDescription>{service.resourceVersion}</DescriptionListDescription>
              </DescriptionListGroup>

              {sd.isAmbient && (
                <DescriptionListGroup data-test="details-ambient">
                  <DescriptionListTerm>{t('Mesh')}</DescriptionListTerm>
                  <DescriptionListDescription>
                    <AmbientLabel tooltip={tooltipMsgType.service} />
                  </DescriptionListDescription>
                </DescriptionListGroup>
              )}

              {service.additionalDetails?.map((additionalItem, idx) => (
                <DescriptionListGroup key={`additional-${idx}`}>
                  <DescriptionListTerm>
                    {additionalItem.title}
                    {additionalItem.icon && renderAPILogo(additionalItem.icon, undefined, idx)}
                  </DescriptionListTerm>
                  <DescriptionListDescription>
                    <TextOrLink text={additionalItem.value} urlTruncate={64} />
                  </DescriptionListDescription>
                </DescriptionListGroup>
              ))}

              {service.selectors && Object.keys(service.selectors).length > 0 && (
                <DescriptionListGroup data-test="details-selector">
                  <DescriptionListTerm>{t('Selector')}</DescriptionListTerm>
                  <DescriptionListDescription>
                    <Labels labels={service.selectors} />
                  </DescriptionListDescription>
                </DescriptionListGroup>
              )}
            </DescriptionList>
          </CardBody>
        </Card>
      </StackItem>
    );
  }

  private renderResourcesCard(): React.ReactNode {
    const sd = this.props.serviceDetails;
    if (!sd) {
      return null;
    }

    const apps: string[] = [];
    const workloads: AppWorkload[] = [];

    if (sd.workloads) {
      sd.workloads
        .sort((w1: WorkloadOverview, w2: WorkloadOverview) => (w1.name < w2.name ? -1 : 1))
        .forEach(wk => {
          if (wk.labels && !wk.isWaypoint && !wk.isZtunnel) {
            const appLabelName = getAppLabelName(wk.labels);
            if (appLabelName) {
              const appName = wk.labels[appLabelName];
              if (!apps.includes(appName)) {
                apps.push(appName);
              }
            }
          }

          workloads.push({
            namespace: wk.namespace,
            workloadName: wk.name,
            gvk: getIstioObjectGVK(wk.resourceVersion, wk.type),
            istioSidecar: wk.istioSidecar,
            isAmbient: wk.isAmbient,
            isGateway: wk.isGateway,
            isWaypoint: wk.isWaypoint,
            isZtunnel: wk.isZtunnel,
            serviceAccountNames: wk.serviceAccountNames,
            labels: wk.labels ?? {},
            spireInfo: wk.spireInfo
          });
        });
    }

    return (
      <StackItem key="resources">
        <Card data-test="service-resources-card" isCompact>
          <CardHeader>
            <Title headingLevel="h4" size={TitleSizes.md}>
              {t('Resources')}
            </Title>
          </CardHeader>
          <CardBody>
            <DetailDescription
              namespace={this.props.namespace}
              apps={apps.length > 0 ? apps : undefined}
              workloads={workloads}
              cluster={sd.service.cluster}
              waypointWorkloads={sd.waypointWorkloads}
            />
          </CardBody>
        </Card>
      </StackItem>
    );
  }

  private renderLabelsCard(): React.ReactNode {
    const sd = this.props.serviceDetails;
    if (!sd) {
      return null;
    }

    return (
      <StackItem key="labels" data-test="service-labels-card">
        <EditableLabelsCard
          canEdit={!serverConfig.deployment.viewOnlyMode}
          isVertical={false}
          labels={sd.service.labels ?? {}}
          numLabels={999}
          onLabelClick={(key, value) => navigateToFilteredList(Paths.SERVICES, key, value, this.props.namespace)}
          onSave={this.props.onSaveLabels}
          prioritizeIstio
          title={t('Labels')}
        />
      </StackItem>
    );
  }

  private renderAnnotationsCard(): React.ReactNode {
    const sd = this.props.serviceDetails;
    if (!sd) {
      return null;
    }

    return (
      <StackItem key="annotations" data-test="service-annotations-card">
        <EditableAnnotationsCard
          annotations={sd.service.annotations ?? {}}
          canEdit={!serverConfig.deployment.viewOnlyMode}
          onSave={this.props.onSaveAnnotations}
          prioritizeIstio
          prioritizeIstioCount
          title={t('Annotations')}
        />
      </StackItem>
    );
  }

  render(): React.ReactNode {
    const vsIstioConfigItems = this.props.serviceDetails?.virtualServices
      ? vsToIstioItems(
          this.props.serviceDetails.virtualServices,
          this.props.serviceDetails.validations,
          this.props.cluster
        )
      : [];

    const drIstioConfigItems = this.props.serviceDetails?.destinationRules
      ? drToIstioItems(
          this.props.serviceDetails.destinationRules,
          this.props.serviceDetails.validations,
          this.props.cluster
        )
      : [];

    const gwIstioConfigItems =
      this.props?.gateways && this.props.serviceDetails?.virtualServices
        ? gwToIstioItems(
            this.props?.gateways,
            this.props.serviceDetails.virtualServices,
            this.props.serviceDetails.validations,
            this.props.cluster
          )
        : [];

    const k8sGwIstioConfigItems =
      this.props?.k8sGateways && (this.props.serviceDetails?.k8sHTTPRoutes || this.props.serviceDetails?.k8sGRPCRoutes)
        ? k8sGwToIstioItems(
            this.props?.k8sGateways,
            this.props.serviceDetails.k8sHTTPRoutes,
            this.props.serviceDetails.k8sGRPCRoutes,
            this.props.serviceDetails.validations,
            this.props.cluster,
            this.props.serviceDetails?.service?.labels
              ? this.props.serviceDetails.service.labels[serverConfig.istioLabels.ambientWaypointGatewayLabel]
              : ''
          )
        : [];

    const seIstioConfigItems = this.props.serviceDetails?.serviceEntries
      ? seToIstioItems(
          this.props.serviceDetails.serviceEntries,
          this.props.serviceDetails.validations,
          this.props.cluster
        )
      : [];

    const k8sHTTPRouteIstioConfigItems = this.props.serviceDetails?.k8sHTTPRoutes
      ? k8sHTTPRouteToIstioItems(
          this.props.serviceDetails.k8sHTTPRoutes,
          this.props.serviceDetails.validations,
          this.props.cluster
        )
      : [];

    const k8sGRPCRouteIstioConfigItems = this.props.serviceDetails?.k8sGRPCRoutes
      ? k8sGRPCRouteToIstioItems(
          this.props.serviceDetails.k8sGRPCRoutes,
          this.props.serviceDetails.validations,
          this.props.cluster
        )
      : [];

    const k8sInferencePoolIstioConfigItems = this.props.serviceDetails?.k8sInferencePools
      ? k8sInferencePoolToIstioItems(this.props.serviceDetails.k8sInferencePools, this.props.cluster)
      : [];

    const istioConfigItems = seIstioConfigItems.concat(
      gwIstioConfigItems.concat(
        k8sGwIstioConfigItems.concat(
          vsIstioConfigItems.concat(
            drIstioConfigItems.concat(
              k8sHTTPRouteIstioConfigItems.concat(k8sGRPCRouteIstioConfigItems.concat(k8sInferencePoolIstioConfigItems))
            )
          )
        )
      )
    );

    const miniGraphSpan = 8;

    return (
      <>
        <div className={flexFillStyle}>
          <Grid hasGutter={true} className={detailGridStyle}>
            <GridItem span={4} className={detailLeftColumnStyle}>
              <Stack style={{ gap: '0.5rem' }}>
                {this.renderDetailsCard()}
                {this.renderResourcesCard()}
                {this.renderLabelsCard()}
                {this.renderAnnotationsCard()}

                {this.props.serviceDetails &&
                  this.props.serviceDetails.workloads &&
                  this.props.serviceDetails.workloads.length > 0 &&
                  this.props.serviceDetails.workloads.some(w => w.spireInfo?.isSpireManaged) && (
                    <StackItem>
                      <Spire object={this.props.serviceDetails} objectType="service" />
                    </StackItem>
                  )}

                {this.props.serviceDetails && (
                  <StackItem>
                    <ServiceNetwork
                      serviceDetails={this.props.serviceDetails}
                      gateways={this.props.gateways}
                      validations={this.getServiceValidation()}
                    />
                  </StackItem>
                )}

                <StackItem style={{ paddingBottom: '20px' }}>
                  <IstioConfigCard name={this.props.service} items={istioConfigItems} />
                </StackItem>
              </Stack>
            </GridItem>

            <GridItem span={miniGraphSpan}>
              <MiniGraphCard
                dataSource={this.graphDataSource}
                onDeleteTrafficRouting={this.handleDeleteTrafficRouting}
                onLaunchWizard={this.handleLaunchWizard}
                serviceDetails={this.props.serviceDetails}
              />
            </GridItem>
          </Grid>
        </div>

        <ServiceWizard
          show={this.state.showWizard}
          type={this.state.wizardType}
          update={this.state.updateMode}
          namespace={this.props.namespace}
          cluster={this.props.cluster}
          serviceName={this.props.serviceDetails?.service?.name ?? ''}
          workloads={this.props.serviceDetails?.workloads ?? []}
          subServices={this.props.serviceDetails?.subServices ?? []}
          createOrUpdate={
            canCreate(this.props.serviceDetails?.istioPermissions) ||
            canUpdate(this.props.serviceDetails?.istioPermissions)
          }
          virtualServices={this.props.serviceDetails?.virtualServices ?? []}
          destinationRules={this.props.serviceDetails?.destinationRules ?? []}
          gateways={getGatewaysAsList(filterAutogeneratedGateways(this.props.gateways))}
          k8sGateways={getK8sGatewaysAsList(this.props.k8sGateways)}
          k8sGRPCRoutes={this.props.serviceDetails?.k8sGRPCRoutes ?? []}
          k8sHTTPRoutes={this.props.serviceDetails?.k8sHTTPRoutes ?? []}
          peerAuthentications={this.props.peerAuthentications}
          tlsStatus={this.props.serviceDetails?.namespaceMTLS}
          onClose={this.handleWizardClose}
        />

        {this.state.showConfirmDeleteTrafficRouting && (
          <ConfirmDeleteTrafficRoutingModal
            destinationRules={DestinationRuleC.fromDrArray(this.props.serviceDetails!.destinationRules)}
            virtualServices={this.props.serviceDetails!.virtualServices}
            k8sHTTPRoutes={this.props.serviceDetails!.k8sHTTPRoutes}
            k8sGRPCRoutes={this.props.serviceDetails!.k8sGRPCRoutes}
            isOpen={true}
            onCancel={() => this.setState({ showConfirmDeleteTrafficRouting: false })}
            onConfirm={this.handleConfirmDeleteServiceTrafficRouting}
          />
        )}
      </>
    );
  }
}

const mapStateToProps = (state: KialiAppState): ReduxProps => ({
  duration: durationSelector(state)
});

export const ServiceInfo = connect(mapStateToProps)(ServiceInfoComponent);
