FROM registry.access.redhat.com/ubi8-minimal

ENV CAI_HOME=/opt/kiali \
    PATH=$CAI_HOME:$PATH

WORKDIR $CAI_HOME

RUN microdnf install -y shadow-utils && \
    microdnf clean all && \
    rm -rf /var/cache/yum && \
    adduser --uid 1000 cai

COPY kiali $CAI_HOME/

ADD console $CAI_HOME/console/

RUN chown -R cai:cai $CAI_HOME/console && \
    chmod -R g=u $CAI_HOME/console

USER 1000

ENTRYPOINT ["${CAI_HOME}/kiali"]
