FROM registry.access.redhat.com/ubi9-minimal AS base-amd64
FROM registry.access.redhat.com/ubi9-minimal AS base-arm64
FROM registry.access.redhat.com/ubi9-minimal AS base-s390x
FROM registry.access.redhat.com/ubi9-minimal AS base-ppc64le

FROM base-${TARGETARCH}

LABEL maintainer="kiali-dev@googlegroups.com"

ENV KIALI_HOME=/opt/kiali
ENV PATH=$KIALI_HOME:$PATH

WORKDIR $KIALI_HOME

RUN microdnf install -y shadow-utils && \
    microdnf clean all && \
    rm -rf /var/cache/yum && \
    adduser --uid 1000 kiali

ARG TARGETARCH
COPY kiali-${TARGETARCH} $KIALI_HOME/kiali

USER 1000

ENTRYPOINT ["/opt/kiali/kiali"]
