FROM registry.access.redhat.com/ubi7-minimal

LABEL maintainer="kiali-dev@googlegroups.com"

ENV KIALI_HOME=/opt/kiali \
    PATH=$KIALI_HOME:$PATH

WORKDIR $KIALI_HOME

COPY kiali $KIALI_HOME/

ADD console $KIALI_HOME/console/

RUN microdnf install -y shadow-utils && \
    microdnf clean all && \
    rm -rf /var/cache/yum && \
    adduser kiali && \
    chown -R kiali:kiali $KIALI_HOME/console && \
    chmod -R g=u $KIALI_HOME/console

USER kiali

ENTRYPOINT ["/opt/kiali/kiali"]
