# don't forget to pass environmet variables to docker run like this:
# podman run -e CYPRESS_BASE_URL=<kiali_url> -e CYPRESS_PASSWD=<passwd> docker-cypress:latest
# more details here https://github.com/kiali/kiali/tree/master/frontend/cypress

# using same baseimage of node as its defined in package.json
FROM cypress/base:14.17.0

# Run as non-root user for MP+/OpenShift
USER node

ENV KIALI_HOME=/opt/kiali
WORKDIR $KIALI_HOME

# copy frontend folder to container
COPY --chown=node:node frontend/ $KIALI_HOME/

# Install Cypress dependencies.
RUN /usr/local/bin/yarn install --frozen-lockfile --force
RUN ls -la

# Run Cypress tests.
CMD ["yarn", "cypress:run:junit"]
