# source https://github.com/istio/istio/blob/master/docker/Dockerfile.distroless
FROM gcr.io/distroless/static-debian11:latest-${TARGETARCH:-amd64} AS distroless_source

LABEL maintainer="kiali-dev@googlegroups.com"

# prepare a base dev to modify file contents
FROM ubuntu:focal as ubuntu_source

# Modify contents of container
COPY --from=distroless_source /etc/ /home/etc
COPY --from=distroless_source /home/nonroot /home/nonroot
RUN echo kiali:x:1000: >> /home/etc/group
RUN echo kiali:x:1000:1000:/home/kiali:/sbin/nologin >> /home/etc/passwd

# Customize distroless with the following:
# - password file
# - groups file
# - /home/nonroot directory
FROM distroless_source
COPY --from=ubuntu_source /home/etc/passwd /etc/passwd
COPY --from=ubuntu_source /home/etc/group /etc/group
COPY --from=ubuntu_source /home/nonroot /home/nonroot

ENV KIALI_HOME=/opt/kiali \
    PATH=$KIALI_HOME:$PATH

WORKDIR $KIALI_HOME

ARG TARGETARCH
COPY kiali-${TARGETARCH} $KIALI_HOME/kiali

COPY --chown=kiali:kiali console/ $KIALI_HOME/console/

USER 1000

ENTRYPOINT ["/opt/kiali/kiali"]
