# ubi9/openssl is essentially ubi9-micro with openssl
FROM registry.access.redhat.com/ubi9/openssl AS base-amd64
FROM registry.access.redhat.com/ubi9/openssl AS base-arm64
FROM registry.access.redhat.com/ubi9/openssl AS base-s390x
FROM registry.access.redhat.com/ubi9/openssl AS base-ppc64le

FROM base-${TARGETARCH}

LABEL maintainer="kiali-dev@googlegroups.com"

# Add kiali user and group
RUN echo kiali:x:1000: >> /etc/group
RUN echo kiali:x:1000:1000:/home/kiali:/sbin/nologin >> /etc/passwd

ENV KIALI_HOME=/opt/kiali \
    PATH=$KIALI_HOME:$PATH

WORKDIR $KIALI_HOME

ARG TARGETARCH
COPY --chown=1000:1000 kiali-${TARGETARCH} $KIALI_HOME/kiali

COPY --chown=1000:1000 console/ $KIALI_HOME/console/

USER 1000

ENTRYPOINT ["/opt/kiali/kiali"]
