FROM registry.access.redhat.com/ubi8/openssl as ca-certs-source
FROM registry.access.redhat.com/ubi8-micro

LABEL maintainer="kiali-dev@googlegroups.com"

# Micro container doesn't have CA certificates, install them now
COPY --from=ca-certs-source /etc/pki /etc/pki
COPY --from=ca-certs-source /usr/share/pki /usr/share/pki

# Add kiali user and group
RUN echo kiali:x:1000: >> /etc/group
RUN echo kiali:x:1000:1000:/home/kiali:/sbin/nologin >> /etc/passwd

ENV KIALI_HOME=/opt/kiali \
    PATH=$KIALI_HOME:$PATH

WORKDIR $KIALI_HOME

COPY --chown=1000:1000 kiali $KIALI_HOME/

COPY --chown=1000:1000 console/ $KIALI_HOME/console/

USER 1000

ENTRYPOINT ["/opt/kiali/kiali"]
