apiVersion: v1
kind: Pod
metadata:
  name: curl-client
spec:
  containers:
  - name: curl-client
    image: curlimages/curl
    command: ["/bin/sh", "-c"]
    args:
    - while true; do echo "Calling echo-service..."; curl -s http://echo-service sleep 5; done;
