== Requirements

- pip
- openshift-python (pip install openshift) (openshift should be 0.6.2+)
- ansible 2.5+


== Installing Bookinfo without Traffic Generator


[NOTE]
All the Bookinfo Demo pods and services are installed in the "bookinfo" namespace by default. If you want to define a different namespace from bookinfo, please set `-e bookinfo_namespace='your_namespace'`


[NOTE]
Bookinfo Version should be defined according to Istio Release. Check https://github.com/istio/istio/blob/master/samples/bookinfo/platform/kube/bookinfo.yaml

- In order to uninstall it, simply delete that namespace via something like `kubectl delete namespace bookinfo` or
`oc delete project bookinfo` (or namespace that you used)

- In order quick install, you may use the following command

```
ansible-playbook install_bookinfo.yml
```

- If you want to include traffic generator to bookinfo project, see sections below

== Installing Bookinfo with Kiali Traffic Generator

[NOTE]
The variable `-e traffic_generator=true` must be present on the command line, if you want traffic generator to be deployed

[NOTE]
Rate is the number of request per seconds that traffic generator will hit the application and this variable is mandatory. It is recommend to use `-e rate=1`

[NOTE]
Rename label is for renamming bookinfo resources. It is recommend to use `-e rename_label=-app`
[NOTE]
You must choose between Ingress Route or Openshift Route there is a traffic generator included

=== Kiali Traffic Generator with Ingress Route
- If you want to use ingress route (all traffic is going to hit ingress-gateway), you may use the following command:

```
ansible-playbook install_bookinfo.yml -e ingress_route=true -e traffic_generator=true -e rate=1 -vv
```

=== Kiali Traffic Generator with Openshift Route

- If you want to use openshift route (kiali will report as "unknown"), you may use the following command:

```
ansible-playbook install_bookinfo.yml -e ingress_route=false -e traffic_generator=true -e rate=1 -vv
```


=== Kiali Traffic Generator with MongoDB

- If you want to enable MongoDB for ratings, you may use the following command

```
ansible-playbook install_bookinfo.yml -e ingress_route=false -e traffic_generator=true -e rate=1 -e mongodb=true -vv
```

=== Kiali Traffic Generator with MySQL

- If you want to enable MySQL for ratings, you may use the following command

```
ansible-playbook install_bookinfo.yml -e ingress_route=false -e traffic_generator=true -e rate=1 -e mysql=true -vv
```
