apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2025-07-15T19:28:09Z"
  labels:
    kubernetes.io/metadata.name: istio-system
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:kubernetes.io/metadata.name: {}
    manager: kubectl-create
    operation: Update
    time: "2025-07-15T19:28:09Z"
  name: istio-system
  resourceVersion: "839"
  uid: c92e9a78-6e7e-4b1d-90fe-e38d07ab5282
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
