apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kiali
  namespace: openshift-operators
spec:
  channel: stable
  source: rhd-workshop-packages
  name: kiali-ossm 
  sourceNamespace: openshift-operators