= Hack Scripts

:toc: macro
:toc-title:

== Description

The following are brief summaries for each hack script. Most of these hack scripts accept a `--help` option to provide information on the different options available.

* `aws-openshift-istio.sh`

Utilizes the `aws-openshift.sh` script to start an OpenShift cluster on AWS, and then utilizes some of the link:./istio[hack scripts in ./istio] to install either Service Mesh or upstream Istio as well as the bookinfo demo. You must have an AWS account as well as an OpenShift pull secret to use this.

* `aws-openshift.sh`

Starts and stops an OpenShift cluster on AWS as well as provides information about the running OpenShift cluster. You must have an AWS account as well as an OpenShift pull secret to use this.

* `check_go_version.sh`

Used by the Kiali server build targets in order to confirm the version of Go is compatible with Kiali.

* `ci-minikube-molecule-tests.sh`

Runs the Kiali molecule tests with the latest version of the Kiali quay.io images on a minikube Kubernetes cluster. This utilizes the `k8s-minikube.sh` script to start and stop a minikube VM and the `run-molecule-tests.sh` script to run the molecule tests. Use this in a cron job to periodically run the molecule tests on minikube.

* `ci-openshift-molecule-tests.sh`

Runs the Kiali molecule tests with the latest version of the Kiali quay.io images on an OpenShift AWS cluster. This utilizes the `aws-openshift-istio.sh` script to start and stop an OpenShift cluster on AWS installed with either Service Mesh or upstream Istio. Also utilizes the `run-molecule-tests.sh` script to run the molecule tests. Use this in a cron job to periodically run the molecule tests on minikube.

* `crc-openshift.sh`

Similar to `aws-openshift.sh` except it runs OpenShift on the local machine using link:https://github.com/code-ready/crc[CRC].

* `jwt-decode.sh`

A testing utility that can be used to decode JWT encoded tokens generated by the Kiali server.

* `jwt-encode.sh`

A testing utility that can be used to encode JWT tokens. Developers use this to generate unauthorized tokens and pass them to Kiali to try to see if the Kiali authentication mechanism can be thwarted.

* `k8s-minikube.sh`

Starts and stops a Kubernetes cluster via minikube as well as provides information about the running Kubernetes cluster. This can optionally install Dex OpenID Connect provider which is useful for testing Kiali's OpenID authentication integration.

* `run-molecule-tests.sh`

Runs the suite of molecule tests on a running OpenShift or minikube cluster.

* `run-prometheus.sh`

Runs a local Prometheus in docker and scrapes the Kiali server and operator that is running in an OpenShift cluster.

== Running Molecule Tests Periodically

If you have a cluster running (in this example, one that was installed locally via link:https://github.com/kxr/ocp4_setup_upi_kvm[ocp4_setup_upi_kvm]), you can use a script like this for a cron job in order to periodically run the Molecule tests:

```
#!/bin/bash

# abort on any error
set -e

ID="/root/ocp4_setup_ocp4/install_dir"
OC="/root/ocp4_setup_ocp4/oc"
SRC="/tmp/KIALI-GIT"
DORP="podman"

# If you want to test code from different forks and/or branches, set them here
KIALI_FORK="kiali"
KIALI_BRANCH="master"
KIALI_OPERATOR_FORK="kiali"
KIALI_OPERATOR_BRANCH="master"

echo "Create a clean github repo location"
rm -rf /tmp/KIALI-GIT
mkdir -p $SRC

echo "Make sure everything exists"
test -d $ID || (echo "$ID is missing"; exit 1)
test -x $OC || (echo "$OC is missing"; exit 1)
test -d $SRC || (echo "$SRC is missing"; exit 1)
which $DORP > /dev/null || (echo "$DORP is not in the PATH"; exit 1)

echo "Clone github repos to make sure we have the latest tests and scripts"
cd $SRC
git clone --single-branch --branch ${KIALI_BRANCH} git@github.com:${KIALI_FORK}/kiali
git clone --single-branch --branch ${KIALI_OPERATOR_BRANCH} git@github.com:${KIALI_OPERATOR_FORK}/kiali-operator kiali/operator
cd kiali

echo "Log into the cluster"
$OC login -u kubeadmin -p $(cat $ID/auth/kubeadmin-password) https://api.ocp4.local:6443

echo "Run the tests"
hack/run-molecule-tests.sh --client-exe "$OC"
```

Note that if you do not have a cluster readily available, you could tweek that script to use `ci-openshift-molecule-tests.sh` or `ci-minikube-molecule-tests.sh` to do everything (install the cluster and then run the molecule tests).
