= Hack Scripts

:toc: macro
:toc-title:

== Description

The following are brief summaries for each hack script. Most of these hack scripts accept a `--help` option to provide information on the different options available.

* `link:aws-openshift-istio.sh[]`

Utilizes the `aws-openshift.sh` script to start an OpenShift cluster on AWS, and then utilizes some of the link:./istio[hack scripts in ./istio] to install either Service Mesh or upstream Istio as well as the bookinfo demo. You must have an AWS account as well as an OpenShift pull secret to use this.

* `link:aws-openshift.sh[]`

Starts and stops an OpenShift cluster on AWS as well as provides information about the running OpenShift cluster. You must have an AWS account as well as an OpenShift pull secret to use this.

* `link:check_go_version.sh[]`

Used by the Kiali server build targets in order to confirm the version of Go is compatible with Kiali.

* `link:ci-minikube-molecule-tests.sh[]`

Runs the Kiali molecule tests with the latest version of the Kiali quay.io images on a minikube Kubernetes cluster. This utilizes the `k8s-minikube.sh` script to start and stop a minikube VM and the `run-molecule-tests.sh` script to run the molecule tests. Use this in a cron job to periodically run the molecule tests on minikube.

* `link:ci-openshift-molecule-tests.sh[]`

Runs the Kiali molecule tests with the latest version of the Kiali quay.io images on an existing OpenShift cluster. Utilizes the `run-molecule-tests.sh` script to run the molecule tests. Use this in a cron job to periodically run the molecule tests.

* `link:crc-openshift.sh[]`

Similar to `aws-openshift.sh` except it runs OpenShift on the local machine using link:https://github.com/code-ready/crc[CRC].

* `link:jwt-decode.sh[]`

A testing utility that can be used to decode JWT encoded tokens generated by the Kiali server.

* `link:jwt-encode.sh[]`

A testing utility that can be used to encode JWT tokens. Developers use this to generate unauthorized tokens and pass them to Kiali to try to see if the Kiali authentication mechanism can be thwarted.

* `link:k8s-minikube.sh[]`

Starts and stops a Kubernetes cluster via minikube as well as provides information about the running Kubernetes cluster. This can optionally install Dex OpenID Connect provider which is useful for testing Kiali's OpenID authentication integration.

* `link:run-molecule-tests.sh[]`

Runs the suite of molecule tests on a running OpenShift or minikube cluster.

* `link:run-prometheus.sh[]`

Runs a local Prometheus in docker and scrapes the Kiali server and operator that is running in an OpenShift cluster.

== Running Molecule Tests Periodically

=== Testing on Minikube

You can do this for a cron job in order to periodically run the Molecule tests on Minikube. If Minikube is not yet started, this script will start one for you (using `k8s-minikube.sh`) with Dex installed so the OIDC tests can run:

```
hack/ci-minikube-molecule-tests.sh
```

There are several options you can pass to that script - pass in `--help` to see what is applicable for you.

=== Testing on OpenShift

If you have a cluster running - one that was installed locally via link:https://github.com/kxr/ocp4_setup_upi_kvm[ocp4_setup_upi_kvm] - you can do this for a cron job in order to periodically run the Molecule tests:

```
hack/ci-openshift-molecule-tests.sh
```

There are several options you can pass to that script - pass in `--help` to see what is applicable for you.
