== Setup Your Own Local OpenShift Cluster with Istio

To start and stop OpenShift with Istio, you use the `cluster-openshift.sh` script:

* You can start it via: `cluster-openshift.sh up`
* You can stop it via: `cluster-openshift.sh down`
* You can get version and status information via: `cluster-openshift.sh status`

These scripts utilize the `istiooc` binary to deploy and start OpenShift with Istio.

If you already have `istiooc` on your machine, you can use it by simply setting `--bin-dir` to the directory where it is located.  If you do not have it, the `cluster-openshift.sh` will download a copy for you in the directory specified by that `--bin-dir` option. If that option is not set, the default is `${HOME}/bin`.

If you need `istiooc` downloaded, the script will download the Linux binary by default. If you are on a Mac, set `--istiooc-platform` to `darwin`.

If you want a specific version of `istiooc`, you can specify it via `istiooc-version`.
You can see the versions available at: https://github.com/openshift-istio/origin/releases

If you wish to install a version of Kiali, you can do so by passing in `--kiali-enabled true`. If you wish to install a specific version of Kiali, you can define that via `--kiali-version VERSION` where VERSION identifies the version string (e.g. v0.5.0). The default credentials to log into Kiali will be `admin`/`admin` unless you specify something else via `--kiali-username` and `--kiali-password`.
(NOTE: this does not work when using older versions of `istiooc` and older Istio versions via the `--istio-version` option).

Execute `cluster-openshift.sh --help` for information on other command line options available.

=== Bookinfo Demo

If you want to install a sample mesh, you can use the link:istio/install-bookinfo-demo.sh[Bookinfo Demo Install Script] as a convenient way to install the Istio Bookinfo Demo. See the link:istio/README.adoc[README] for more.

=== Installing A Specific Istio Version

If you wish to install a specific version of Istio, you can pass in `--istio-version` to the `cluster-openshift.sh` hack script.
For example, to install Istio 0.7.1:

```
cluster-openshift.sh --istio-version 0.7.1
```
