---
apiVersion: v1
items:
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2025-07-15T19:29:53Z"
    creationTimestamp: "2025-07-15T19:29:37Z"
    labels:
      app: v-server
      endpoints.kubernetes.io/managed-by: endpoint-controller
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:labels:
            .: {}
            f:app: {}
            f:endpoints.kubernetes.io/managed-by: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2025-07-15T19:29:53Z"
    name: v-server
    namespace: beta
    resourceVersion: "2827"
    uid: 4205a5f9-9313-4eb5-8d32-c88f95a8ea75
  subsets:
  - addresses:
    - ip: 10.244.1.34
      nodeName: ci-worker
      targetRef:
        kind: Pod
        name: v-server-54b77ffd4f-rdg2v
        namespace: beta
        uid: 2f490541-acb7-45e6-8ac5-cee5f6760155
    ports:
    - name: http
      port: 8888
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2025-07-15T19:29:53Z"
    creationTimestamp: "2025-07-15T19:29:37Z"
    labels:
      app: w-server
      endpoints.kubernetes.io/managed-by: endpoint-controller
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:labels:
            .: {}
            f:app: {}
            f:endpoints.kubernetes.io/managed-by: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2025-07-15T19:29:53Z"
    name: w-server
    namespace: beta
    resourceVersion: "2813"
    uid: 877f175c-df3c-4878-910c-758faec772cc
  subsets:
  - addresses:
    - ip: 10.244.1.35
      nodeName: ci-worker
      targetRef:
        kind: Pod
        name: w-server-8667cdbcf7-mbqvb
        namespace: beta
        uid: 57c7395e-7658-4586-8aa2-89421b9ccc5c
    ports:
    - name: http
      port: 8888
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2025-07-15T19:29:53Z"
    creationTimestamp: "2025-07-15T19:29:37Z"
    labels:
      app: x-server
      endpoints.kubernetes.io/managed-by: endpoint-controller
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:labels:
            .: {}
            f:app: {}
            f:endpoints.kubernetes.io/managed-by: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2025-07-15T19:29:53Z"
    name: x-server
    namespace: beta
    resourceVersion: "2822"
    uid: 59a9c369-b221-42af-9dbf-95f972f997bc
  subsets:
  - addresses:
    - ip: 10.244.1.36
      nodeName: ci-worker
      targetRef:
        kind: Pod
        name: x-server-6d8987d7c7-lcljz
        namespace: beta
        uid: 005f1bb8-7fb3-4aec-82ce-8ba6128d1409
    ports:
    - name: http
      port: 8888
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2025-07-15T19:29:54Z"
    creationTimestamp: "2025-07-15T19:29:37Z"
    labels:
      app: y-server
      endpoints.kubernetes.io/managed-by: endpoint-controller
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:labels:
            .: {}
            f:app: {}
            f:endpoints.kubernetes.io/managed-by: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2025-07-15T19:29:54Z"
    name: y-server
    namespace: beta
    resourceVersion: "2861"
    uid: 7bcaa689-cc67-472e-85f7-1a590bf1be6f
  subsets:
  - addresses:
    - ip: 10.244.1.37
      nodeName: ci-worker
      targetRef:
        kind: Pod
        name: y-server-5b556546fd-ssp2m
        namespace: beta
        uid: eecd22ca-ac74-486d-82a9-1b347d2a9b3f
    ports:
    - name: http
      port: 8888
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2025-07-15T19:29:53Z"
    creationTimestamp: "2025-07-15T19:29:37Z"
    labels:
      app: z-server
      endpoints.kubernetes.io/managed-by: endpoint-controller
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:labels:
            .: {}
            f:app: {}
            f:endpoints.kubernetes.io/managed-by: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2025-07-15T19:29:53Z"
    name: z-server
    namespace: beta
    resourceVersion: "2836"
    uid: 79fedac9-8595-45da-bc24-2a2d020323bd
  subsets:
  - addresses:
    - ip: 10.244.1.38
      nodeName: ci-worker
      targetRef:
        kind: Pod
        name: z-server-5f94f449c5-qwb7f
        namespace: beta
        uid: 5d2e193a-5a27-4f22-a72e-f0101c1854da
    ports:
    - name: http
      port: 8888
      protocol: TCP
kind: EndpointsList
metadata:
  resourceVersion: "5099"
