---
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"v-server"},"name":"v-server","namespace":"beta"},"spec":{"ports":[{"name":"http","port":8888}],"selector":{"app":"v-server"}}}
    creationTimestamp: "2025-07-15T19:29:37Z"
    labels:
      app: v-server
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:labels:
            .: {}
            f:app: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":8888,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: "2025-07-15T19:29:37Z"
    name: v-server
    namespace: beta
    resourceVersion: "1854"
    uid: 41e32bf9-6728-4901-accf-f38eb7c014c2
  spec:
    clusterIP: 10.96.125.0
    clusterIPs:
    - 10.96.125.0
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 8888
      protocol: TCP
      targetPort: 8888
    selector:
      app: v-server
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"w-server"},"name":"w-server","namespace":"beta"},"spec":{"ports":[{"name":"http","port":8888}],"selector":{"app":"w-server"}}}
    creationTimestamp: "2025-07-15T19:29:37Z"
    labels:
      app: w-server
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:labels:
            .: {}
            f:app: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":8888,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: "2025-07-15T19:29:37Z"
    name: w-server
    namespace: beta
    resourceVersion: "1862"
    uid: ea104a28-1773-4b18-adff-c129e1e7249a
  spec:
    clusterIP: 10.96.124.163
    clusterIPs:
    - 10.96.124.163
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 8888
      protocol: TCP
      targetPort: 8888
    selector:
      app: w-server
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"x-server"},"name":"x-server","namespace":"beta"},"spec":{"ports":[{"name":"http","port":8888}],"selector":{"app":"x-server"}}}
    creationTimestamp: "2025-07-15T19:29:37Z"
    labels:
      app: x-server
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:labels:
            .: {}
            f:app: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":8888,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: "2025-07-15T19:29:37Z"
    name: x-server
    namespace: beta
    resourceVersion: "1868"
    uid: 8bb2e777-f074-40b4-b7cd-2d937900f146
  spec:
    clusterIP: 10.96.154.89
    clusterIPs:
    - 10.96.154.89
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 8888
      protocol: TCP
      targetPort: 8888
    selector:
      app: x-server
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"y-server"},"name":"y-server","namespace":"beta"},"spec":{"ports":[{"name":"http","port":8888}],"selector":{"app":"y-server"}}}
    creationTimestamp: "2025-07-15T19:29:37Z"
    labels:
      app: y-server
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:labels:
            .: {}
            f:app: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":8888,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: "2025-07-15T19:29:37Z"
    name: y-server
    namespace: beta
    resourceVersion: "1874"
    uid: ecb62cb6-a855-4a62-a582-1e92201dff8e
  spec:
    clusterIP: 10.96.185.77
    clusterIPs:
    - 10.96.185.77
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 8888
      protocol: TCP
      targetPort: 8888
    selector:
      app: y-server
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"z-server"},"name":"z-server","namespace":"beta"},"spec":{"ports":[{"name":"http","port":8888}],"selector":{"app":"z-server"}}}
    creationTimestamp: "2025-07-15T19:29:37Z"
    labels:
      app: z-server
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:labels:
            .: {}
            f:app: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":8888,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: "2025-07-15T19:29:37Z"
    name: z-server
    namespace: beta
    resourceVersion: "1882"
    uid: 386c7eed-5934-4b54-aeb3-5e025f7ca9b4
  spec:
    clusterIP: 10.96.60.176
    clusterIPs:
    - 10.96.60.176
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 8888
      protocol: TCP
      targetPort: 8888
    selector:
      app: z-server
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: ServiceList
metadata:
  resourceVersion: "5098"
