---
dependency:
  name: galaxy
platforms:
- name: default
  groups:
  - k8s
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: junit
  playbooks:
    destroy: ../default/destroy.yml
    prepare: ../default/prepare.yml
  inventory:
    group_vars:
      all:
        kiali_operator_assets_path : "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/deploy"
        cr_file_path: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/molecule/rolling-restart-test/kiali-cr.yaml"
        istio:
          control_plane_namespace: istio-system
        kiali:
          accessible_namespaces: ["**"]
          auth_strategy: openshift
          operator_namespace: kiali-operator
          operator_image_name: quay.io/kiali/kiali-operator
          operator_version: latest
          #operator_image_name: image-registry.openshift-image-registry.svc:5000/kiali/kiali-operator
          #operator_version: dev
          operator_watch_namespace: kiali-operator
          operator_clusterrolebindings: "- clusterrolebindings"
          operator_clusterroles: "- clusterroles"
          image_name: quay.io/kiali/kiali
          image_version: latest
          image_pull_policy: Always
scenario:
  name: rolling-restart-test
  test_sequence:
  - prepare
  - converge
  - destroy
