apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-cluster-observability-operator
  namespace: ${OPERATOR_NAMESPACE}
spec:
  channel: stable
  installPlanApproval: Automatic
  name: cluster-observability-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace

