apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-opentelemetry-operator
  namespace: ${OPERATOR_NAMESPACE}
spec:
  channel: stable
  installPlanApproval: Automatic
  name: opentelemetry-product
  source: redhat-operators
  sourceNamespace: openshift-marketplace

