const fs = require('fs');
const path = require('path');

const conversationsDir = path.resolve(__dirname, '../handlers/chatbot/conversations');
const outputPath = path.resolve(__dirname, '../handlers/chatbot/conversations.index.ts');

const toIdentifier = fileName => {
  const base = fileName.replace(/\.json$/, '');
  let identifier = base.replace(/[^A-Za-z0-9_]/g, '_');
  if (/^\d/.test(identifier)) {
    identifier = `_${identifier}`;
  }
  return identifier;
};

const files = fs
  .readdirSync(conversationsDir)
  .filter(fileName => fileName.endsWith('.json'))
  .sort((left, right) => left.localeCompare(right));

const imports = files
  .map(fileName => `import ${toIdentifier(fileName)} from './conversations/${fileName}';`)
  .join('\n');

const entries = files
  .map(fileName => {
    const id = fileName.replace(/\.json$/, '');
    return `  ['${id}', ${toIdentifier(fileName)}],`;
  })
  .join('\n');

const content = `// This file is auto-generated by scripts/generateChatbotConversations.js. Do not edit manually.
${imports}

export const conversationModuleEntries: Array<[string, unknown]> = [
${entries}
];
`;

fs.writeFileSync(outputPath, content);
