---
apiVersion: v1
items:
- apiVersion: v1
  data:
    ca-cert.pem: MTA5OSBieXRlcyBsb25n
    ca-key.pem: MTY3NSBieXRlcyBsb25n
    cert-chain.pem: MCBieXRlcyBsb25n
    key.pem: MCBieXRlcyBsb25n
    root-cert.pem: MTA5OSBieXRlcyBsb25n
  kind: Secret
  metadata:
    creationTimestamp: "2025-07-15T19:28:17Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:ca-cert.pem: {}
          f:ca-key.pem: {}
          f:cert-chain.pem: {}
          f:key.pem: {}
          f:root-cert.pem: {}
        f:type: {}
      manager: pilot-discovery
      operation: Update
      time: "2025-07-15T19:28:17Z"
    name: istio-ca-secret
    namespace: istio-system
    resourceVersion: "918"
    uid: 2d14a36a-b3fd-4665-bd57-0ea9761ae3da
  type: istio.io/ca-root
- apiVersion: v1
  data:
    release: ODQwMjQgYnl0ZXMgbG9uZw==
  kind: Secret
  metadata:
    creationTimestamp: "2025-07-15T19:29:43Z"
    labels:
      modifiedAt: "1752607691"
      name: default-istiod
      owner: helm
      status: superseded
      version: "13"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:release: {}
        f:metadata:
          f:labels:
            .: {}
            f:modifiedAt: {}
            f:name: {}
            f:owner: {}
            f:status: {}
            f:version: {}
        f:type: {}
      manager: sail-operator
      operation: Update
      time: "2025-07-15T19:29:46Z"
    name: sh.helm.release.v1.default-istiod.v13
    namespace: istio-system
    resourceVersion: "2524"
    uid: a62e3257-2938-41ac-b1c1-5d0baa16cc3c
  type: helm.sh/release.v1
- apiVersion: v1
  data:
    release: ODQwMTIgYnl0ZXMgbG9uZw==
  kind: Secret
  metadata:
    creationTimestamp: "2025-07-15T19:29:46Z"
    labels:
      modifiedAt: "1752607691"
      name: default-istiod
      owner: helm
      status: deployed
      version: "14"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:release: {}
        f:metadata:
          f:labels:
            .: {}
            f:modifiedAt: {}
            f:name: {}
            f:owner: {}
            f:status: {}
            f:version: {}
        f:type: {}
      manager: sail-operator
      operation: Update
      time: "2025-07-15T19:29:46Z"
    name: sh.helm.release.v1.default-istiod.v14
    namespace: istio-system
    resourceVersion: "2525"
    uid: e4cd1104-e6b3-4614-9803-24487f89d676
  type: helm.sh/release.v1
- apiVersion: v1
  data:
    release: MjA3NDAgYnl0ZXMgbG9uZw==
  kind: Secret
  metadata:
    creationTimestamp: "2025-07-15T19:28:26Z"
    labels:
      modifiedAt: "1752607706"
      name: kiali-server
      owner: helm
      status: deployed
      version: "1"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:release: {}
        f:metadata:
          f:labels:
            .: {}
            f:modifiedAt: {}
            f:name: {}
            f:owner: {}
            f:status: {}
            f:version: {}
        f:type: {}
      manager: helm
      operation: Update
      time: "2025-07-15T19:28:26Z"
    name: sh.helm.release.v1.kiali-server.v1
    namespace: istio-system
    resourceVersion: "1103"
    uid: ed3f8c56-cf94-4597-9100-9e20017c8db7
  type: helm.sh/release.v1
kind: SecretList
metadata:
  resourceVersion: "5060"
