---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    prometheus.io/port: "15014"
    prometheus.io/scrape: "true"
    sidecar.istio.io/inject: "false"
  creationTimestamp: "2025-07-15T19:28:11Z"
  generateName: istiod-58cf6dd64-
  generation: 1
  labels:
    app: istiod
    app.kubernetes.io/instance: default-istiod
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: istiod
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/version: 1.26.2
    helm.sh/chart: istiod-1.26.2
    istio: pilot
    istio.io/dataplane-mode: none
    istio.io/rev: default
    operator.istio.io/component: Pilot
    pod-template-hash: 58cf6dd64
    sidecar.istio.io/inject: "false"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:prometheus.io/port: {}
          f:prometheus.io/scrape: {}
          f:sidecar.istio.io/inject: {}
        f:generateName: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/part-of: {}
          f:app.kubernetes.io/version: {}
          f:helm.sh/chart: {}
          f:istio: {}
          f:istio.io/dataplane-mode: {}
          f:istio.io/rev: {}
          f:operator.istio.io/component: {}
          f:pod-template-hash: {}
          f:sidecar.istio.io/inject: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"fbc06734-7e1b-4da8-a98d-e9152121de8a"}: {}
      f:spec:
        f:containers:
          k:{"name":"discovery"}:
            .: {}
            f:args: {}
            f:env:
              .: {}
              k:{"name":"CA_TRUSTED_NODE_ACCOUNTS"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"CLUSTER_ID"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"GOMAXPROCS"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:resourceFieldRef: {}
              k:{"name":"GOMEMLIMIT"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:resourceFieldRef: {}
              k:{"name":"KUBECONFIG"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"PILOT_CERT_PROVIDER"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"PILOT_ENABLE_ANALYSIS"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"PILOT_TRACE_SAMPLING"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"PLATFORM"}:
                .: {}
                f:name: {}
              k:{"name":"POD_NAME"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:fieldRef: {}
              k:{"name":"POD_NAMESPACE"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:fieldRef: {}
              k:{"name":"REVISION"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"SERVICE_ACCOUNT"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:fieldRef: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:ports:
              .: {}
              k:{"containerPort":8080,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:name: {}
                f:protocol: {}
              k:{"containerPort":15010,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:name: {}
                f:protocol: {}
              k:{"containerPort":15012,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:name: {}
                f:protocol: {}
              k:{"containerPort":15014,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:name: {}
                f:protocol: {}
              k:{"containerPort":15017,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:name: {}
                f:protocol: {}
            f:readinessProbe:
              .: {}
              f:failureThreshold: {}
              f:httpGet:
                .: {}
                f:path: {}
                f:port: {}
                f:scheme: {}
              f:initialDelaySeconds: {}
              f:periodSeconds: {}
              f:successThreshold: {}
              f:timeoutSeconds: {}
            f:resources:
              .: {}
              f:requests:
                .: {}
                f:cpu: {}
                f:memory: {}
            f:securityContext:
              .: {}
              f:allowPrivilegeEscalation: {}
              f:capabilities:
                .: {}
                f:drop: {}
              f:readOnlyRootFilesystem: {}
              f:runAsNonRoot: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:volumeMounts:
              .: {}
              k:{"mountPath":"/etc/cacerts"}:
                .: {}
                f:mountPath: {}
                f:name: {}
                f:readOnly: {}
              k:{"mountPath":"/var/run/secrets/istio-dns"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/var/run/secrets/istiod/ca"}:
                .: {}
                f:mountPath: {}
                f:name: {}
                f:readOnly: {}
              k:{"mountPath":"/var/run/secrets/istiod/tls"}:
                .: {}
                f:mountPath: {}
                f:name: {}
                f:readOnly: {}
              k:{"mountPath":"/var/run/secrets/remote"}:
                .: {}
                f:mountPath: {}
                f:name: {}
                f:readOnly: {}
              k:{"mountPath":"/var/run/secrets/tokens"}:
                .: {}
                f:mountPath: {}
                f:name: {}
                f:readOnly: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext: {}
        f:serviceAccount: {}
        f:serviceAccountName: {}
        f:terminationGracePeriodSeconds: {}
        f:tolerations: {}
        f:volumes:
          .: {}
          k:{"name":"cacerts"}:
            .: {}
            f:name: {}
            f:secret:
              .: {}
              f:defaultMode: {}
              f:optional: {}
              f:secretName: {}
          k:{"name":"istio-csr-ca-configmap"}:
            .: {}
            f:configMap:
              .: {}
              f:defaultMode: {}
              f:name: {}
              f:optional: {}
            f:name: {}
          k:{"name":"istio-csr-dns-cert"}:
            .: {}
            f:name: {}
            f:secret:
              .: {}
              f:defaultMode: {}
              f:optional: {}
              f:secretName: {}
          k:{"name":"istio-kubeconfig"}:
            .: {}
            f:name: {}
            f:secret:
              .: {}
              f:defaultMode: {}
              f:optional: {}
              f:secretName: {}
          k:{"name":"istio-token"}:
            .: {}
            f:name: {}
            f:projected:
              .: {}
              f:defaultMode: {}
              f:sources: {}
          k:{"name":"local-certs"}:
            .: {}
            f:emptyDir:
              .: {}
              f:medium: {}
            f:name: {}
    manager: kube-controller-manager
    operation: Update
    time: "2025-07-15T19:28:11Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"PodReadyToStartContainers"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:hostIPs: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"10.244.1.4"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: kubelet
    operation: Update
    subresource: status
    time: "2025-07-15T19:28:17Z"
  name: istiod-58cf6dd64-s4rq9
  namespace: istio-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: istiod-58cf6dd64
    uid: fbc06734-7e1b-4da8-a98d-e9152121de8a
  resourceVersion: "939"
  uid: ade0abd0-079a-4f84-9469-e90c99074139
spec:
  containers:
  - args:
    - discovery
    - --monitoringAddr=:15014
    - --log_output_level=default:info
    - --domain
    - cluster.local
    - --keepaliveMaxServerConnectionAge
    - 30m
    env:
    - name: REVISION
      value: default
    - name: PILOT_CERT_PROVIDER
      value: istiod
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: SERVICE_ACCOUNT
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.serviceAccountName
    - name: KUBECONFIG
      value: /var/run/secrets/remote/config
    - name: CA_TRUSTED_NODE_ACCOUNTS
      value: istio-system/ztunnel
    - name: PILOT_TRACE_SAMPLING
      value: "1"
    - name: PILOT_ENABLE_ANALYSIS
      value: "false"
    - name: CLUSTER_ID
      value: cluster-default
    - name: GOMEMLIMIT
      valueFrom:
        resourceFieldRef:
          divisor: "1"
          resource: limits.memory
    - name: GOMAXPROCS
      valueFrom:
        resourceFieldRef:
          divisor: "1"
          resource: limits.cpu
    - name: PLATFORM
    image: gcr.io/istio-release/pilot:1.26.2
    imagePullPolicy: IfNotPresent
    name: discovery
    ports:
    - containerPort: 8080
      name: http-debug
      protocol: TCP
    - containerPort: 15010
      name: grpc-xds
      protocol: TCP
    - containerPort: 15012
      name: tls-xds
      protocol: TCP
    - containerPort: 15017
      name: https-webhooks
      protocol: TCP
    - containerPort: 15014
      name: http-monitoring
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /ready
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 3
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      requests:
        cpu: 1m
        memory: 1Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/tokens
      name: istio-token
      readOnly: true
    - mountPath: /var/run/secrets/istio-dns
      name: local-certs
    - mountPath: /etc/cacerts
      name: cacerts
      readOnly: true
    - mountPath: /var/run/secrets/remote
      name: istio-kubeconfig
      readOnly: true
    - mountPath: /var/run/secrets/istiod/tls
      name: istio-csr-dns-cert
      readOnly: true
    - mountPath: /var/run/secrets/istiod/ca
      name: istio-csr-ca-configmap
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-kt4v9
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: ci-worker
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: istiod
  serviceAccountName: istiod
  terminationGracePeriodSeconds: 30
  tolerations:
  - key: cni.istio.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir:
      medium: Memory
    name: local-certs
  - name: istio-token
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          audience: istio-ca
          expirationSeconds: 43200
          path: istio-token
  - name: cacerts
    secret:
      defaultMode: 420
      optional: true
      secretName: cacerts
  - name: istio-kubeconfig
    secret:
      defaultMode: 420
      optional: true
      secretName: istio-kubeconfig
  - name: istio-csr-dns-cert
    secret:
      defaultMode: 420
      optional: true
      secretName: istiod-tls
  - configMap:
      defaultMode: 420
      name: istio-ca-root-cert
      optional: true
    name: istio-csr-ca-configmap
  - name: kube-api-access-kt4v9
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-07-15T19:28:17Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-07-15T19:28:11Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-07-15T19:28:17Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-07-15T19:28:17Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-07-15T19:28:11Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - allocatedResources:
      cpu: 1m
      memory: 1Mi
    containerID: containerd://894ecf2ddc253f759662d5c1b9096031240381822c70588437c64030c8418217
    image: gcr.io/istio-release/pilot:1.26.2
    imageID: gcr.io/istio-release/pilot@sha256:1d4fbb7859e515b85b6c2c4787224e4e7cba73aad4573d98e2a83cc028cad392
    lastState: {}
    name: discovery
    ready: true
    resources:
      requests:
        cpu: 1m
        memory: 1Mi
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-07-15T19:28:16Z"
  hostIP: 172.18.0.3
  hostIPs:
  - ip: 172.18.0.3
  phase: Running
  podIP: 10.244.1.4
  podIPs:
  - ip: 10.244.1.4
  qosClass: Burstable
  startTime: "2025-07-15T19:28:11Z"
