run:
  timeout: 5m
  tests: true
issues:
  exclude:
  - frontend/frontend.go
  exclude-files:
  - doc.go
  - frontend/frontend.go
  - ".*\\.pb\\.go$"
  exclude-dirs:
  - frontend
  - local
linters:
  enable:
  - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/kiali/kiali
