- name: "Create resource [{{ process_resource_item}}] on [{{ process_resource_cluster}}]"
  k8s:
    state: "present"
    definition: "{{ lookup('template', 'templates/' + process_resource_cluster + '/' + process_resource_item + '.yaml') }}"
  register: process_resource_result
  until:
  - process_resource_result.error is not defined
  - process_resource_result.result is defined
  - process_resource_result.result.metadata is defined
  retries: 6
  delay: 10

# Store the results of the processed resource so they can be examined later (e.g. to know if something changed or stayed the same)
- set_fact:
    processed_resources: "{{ processed_resources | default({}) | combine( { process_resource_item: { 'changed': process_resource_result.changed, 'method': process_resource_result.method } } ) }}"
