apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
spec:
  version: default
  istio_namespace: {{ istio.control_plane_namespace }}
  auth:
    strategy: {{ kiali.auth_strategy }}
  deployment:
    # For this test, we do not define namespace.
    # It should default to the location where this CR lives
    # namespace:
    image_name: {{ kiali.image_name }}
    image_pull_policy: {{ kiali.image_pull_policy }}
    image_version: {{ kiali.image_version }}
    accessible_namespaces: {{ kiali.accessible_namespaces }}
