##########
# This enables mTLS at service mesh level.
# The MeshPolicy allows all the services to receive traffic in mTLS mode.
# The DestinationRule allows all the entities to start communications in mTLS mode.
##########
---
apiVersion: "authentication.istio.io/v1alpha1"
kind: "MeshPolicy"
metadata:
  name: "default"
spec:
  peers:
  - mtls: {}
---
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "default"
  namespace: "istio-system"
spec:
  host: "*.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
