name: 'Report to ReportPortal'
description: 'Upload test results to ReportPortal'
inputs:
  test_suite:
    description: 'Test suite name'
    required: true
  test_results_dir:
    description: 'Directory containing test results'
    required: false
    default: '/tmp/artifacts'
  test_file_name:
    description: 'Test results file name'
    required: false
    default: 'junit.xml'
  kiali_version:
    description: 'Kiali version'
    required: false
    default: 'unknown'
  istio_version:
    description: 'Istio version'
    required: false
    default: 'unknown'
  data_plane_mode:
    description: 'Data plane mode'
    required: false
    default: 'unknown'
  pr_number:
    description: 'Pull request number'
    required: false
    default: 'unknown'
  target_branch:
    description: 'Target branch name'
    required: false
    default: 'unknown'
  data_router_username:
    description: 'Data Router username (secret)'
    required: true
  data_router_password:
    description: 'Data Router password (secret)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Download ReportPortal script
      shell: bash
      run: |
        curl -sSL -o /tmp/send_report_portal_results.sh \
          https://raw.githubusercontent.com/openshift-service-mesh/ci-utils/main/report_portal/send_report_portal_results.sh
        chmod +x /tmp/send_report_portal_results.sh

    - name: Set EXTRA_ATTRIBUTES
      shell: bash
      run: |
        echo "EXTRA_ATTRIBUTES=[{\"key\": \"build_type\", \"value\": \"pr_build\"}, {\"key\": \"kiali_version\", \"value\": \"${{ inputs.kiali_version }}\"}, {\"key\": \"istio_version\", \"value\": \"${{ inputs.istio_version }}\"}, {\"key\": \"data_plane_mode\", \"value\": \"${{ inputs.data_plane_mode }}\"}, {\"key\": \"pr_number\", \"value\": \"${{ inputs.pr_number }}\"}, {\"key\": \"target_branch\", \"value\": \"${{ inputs.target_branch }}\"}]" >> $GITHUB_ENV

    - name: Send results to ReportPortal
      shell: bash
      env:
        REPORT_PORTAL_HOSTNAME: reportportal-ossm.apps.dno.ocp-hub.prod.psi.redhat.com
        REPORT_PORTAL_PROJECT: osssm_general
        DATA_ROUTER_USERNAME: ${{ inputs.data_router_username }}
        DATA_ROUTER_PASSWORD: ${{ inputs.data_router_password }}
        TEST_RESULTS_DIR: ${{ inputs.test_results_dir }}
        TEST_FILE_NAME: ${{ inputs.test_file_name }}
        TEST_SUITE: ${{ inputs.test_suite }}
        TESTRUN_NAME: Kiali ${{ inputs.test_suite }} test run
        TESTRUN_DESCRIPTION: Kiali ${{ inputs.test_suite }} test run - PR https://github.com/${{ github.repository }}/pull/${{ inputs.pr_number }}
        INSTALLATION_METHOD: helm
        PRODUCT_STAGE: upstream
        TEST_REPO: ${{ github.repository }}
        EXTRA_ATTRIBUTES: ${{ env.EXTRA_ATTRIBUTES }}
      run: /tmp/send_report_portal_results.sh --verbose
