---
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"v-server"},"name":"v-server","namespace":"alpha"},"spec":{"ports":[{"name":"http","port":8888}],"selector":{"app":"v-server"}}}
    creationTimestamp: "2025-07-15T19:29:37Z"
    labels:
      app: v-server
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:labels:
            .: {}
            f:app: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":8888,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: "2025-07-15T19:29:37Z"
    name: v-server
    namespace: alpha
    resourceVersion: "1762"
    uid: 5b7ec501-3241-44ba-a6db-e55b1a3f6a04
  spec:
    clusterIP: 10.96.240.193
    clusterIPs:
    - 10.96.240.193
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 8888
      protocol: TCP
      targetPort: 8888
    selector:
      app: v-server
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"w-server"},"name":"w-server","namespace":"alpha"},"spec":{"ports":[{"name":"http","port":8888}],"selector":{"app":"w-server"}}}
    creationTimestamp: "2025-07-15T19:29:37Z"
    labels:
      app: w-server
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:labels:
            .: {}
            f:app: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":8888,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: "2025-07-15T19:29:37Z"
    name: w-server
    namespace: alpha
    resourceVersion: "1774"
    uid: 5a6cae50-497f-418f-abe3-24377136b062
  spec:
    clusterIP: 10.96.168.158
    clusterIPs:
    - 10.96.168.158
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 8888
      protocol: TCP
      targetPort: 8888
    selector:
      app: w-server
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"x-server"},"name":"x-server","namespace":"alpha"},"spec":{"ports":[{"name":"http","port":8888}],"selector":{"app":"x-server"}}}
    creationTimestamp: "2025-07-15T19:29:37Z"
    labels:
      app: x-server
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:labels:
            .: {}
            f:app: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":8888,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: "2025-07-15T19:29:37Z"
    name: x-server
    namespace: alpha
    resourceVersion: "1782"
    uid: 69fad82e-6ea0-4746-a806-0e2574960e80
  spec:
    clusterIP: 10.96.139.175
    clusterIPs:
    - 10.96.139.175
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 8888
      protocol: TCP
      targetPort: 8888
    selector:
      app: x-server
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"y-server"},"name":"y-server","namespace":"alpha"},"spec":{"ports":[{"name":"http","port":8888}],"selector":{"app":"y-server"}}}
    creationTimestamp: "2025-07-15T19:29:37Z"
    labels:
      app: y-server
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:labels:
            .: {}
            f:app: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":8888,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: "2025-07-15T19:29:37Z"
    name: y-server
    namespace: alpha
    resourceVersion: "1791"
    uid: cf0f1aa1-efb0-4b09-8a53-0777710839bd
  spec:
    clusterIP: 10.96.234.108
    clusterIPs:
    - 10.96.234.108
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 8888
      protocol: TCP
      targetPort: 8888
    selector:
      app: y-server
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"z-server"},"name":"z-server","namespace":"alpha"},"spec":{"ports":[{"name":"http","port":8888}],"selector":{"app":"z-server"}}}
    creationTimestamp: "2025-07-15T19:29:37Z"
    labels:
      app: z-server
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:labels:
            .: {}
            f:app: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":8888,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: "2025-07-15T19:29:37Z"
    name: z-server
    namespace: alpha
    resourceVersion: "1797"
    uid: ea2ccf20-0d72-445c-8ac3-d2d6111fe740
  spec:
    clusterIP: 10.96.152.221
    clusterIPs:
    - 10.96.152.221
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 8888
      protocol: TCP
      targetPort: 8888
    selector:
      app: z-server
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: ServiceList
metadata:
  resourceVersion: "5071"
