additional_display_details:
- annotation: kiali.io/api-spec
  icon_annotation: kiali.io/api-type
  title: API Documentation
kiali_internal:
  graph_cache:
    enabled: false
  health_cache:
    enabled: false
