health_config:
  rate:
  - kind: service
    name: y-server
    namespace: alpha
    tolerance:
    - code: 5xx
      degraded: 2
      failure: 100
additional_display_details:
- title: API Documentation
  annotation: kiali.io/api-spec
  icon_annotation: kiali.io/api-type
external_services:
  perses:
    dashboards:
    - name: Istio Mesh Dashboard
      variables:
        datasource: var-datasource
        namespace: var-namespace
        workload: var-workload
    enabled: true
    external_url: http://localhost:4000
    internal_url: http://perses.istio-system:8080
kiali_internal:
  graph_cache:
    enabled: false
  health_cache:
    enabled: false
