name: Build Backend

on:
  workflow_call:
    inputs:
      build_branch:
        required: true
        type: string
jobs:
  build_backend:
    name: Build backend binary
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        ref: ${{ inputs.build_branch }}

    - name: Set up Go
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
      with:
        go-version-file: go.mod
        cache: true
        cache-dependency-path: go.sum

    - name: Download frontend build
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
      with:
        name: build
        path: frontend/build

    - name: Build
      run: make -e GO_BUILD_FLAGS=${{ env.GO_BUILD_FLAGS }} -e CGO_ENABLED=${{ env.CGO_ENABLED }} clean build
      env:
        # Build with -race flag if this is a PR, otherwise it is a release and
        # we don't want to build with race detection because of the perf penalty.
        GO_BUILD_FLAGS: ${{ github.base_ref && '-race' }}
        # The -race flag requires CGO_ENABLED
        CGO_ENABLED: ${{ github.base_ref && '1' }}

    - name: Upload go binary
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
      with:
        name: kiali
        path: ~/go/bin/kiali
