name: Check Frontend

on:
  workflow_call:
    inputs:
      target_branch:
        required: true
        type: string
      build_branch:
        required: true
        type: string

jobs:
  check_frontend:
    name: Check and unit test frontend
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.build_branch }}

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: "20"
        cache: yarn
        cache-dependency-path: frontend/yarn.lock

    - name: Build
      run: make clean-all build-ui check-ui-build

    - name: Test frontend
      run: |
        cd frontend
        yarn pretty-quick --check --verbose --branch ${{ inputs.target_branch }}
        yarn test
