name: Integration Tests Backend External Controlplane

on:
  workflow_call:
    inputs:
      target_branch:
        required: true
        type: string
      build_branch:
        required: true
        type: string
      istio_version:
        required: false
        type: string
        default: ""

env:
  TARGET_BRANCH: ${{ inputs.target_branch }}

jobs:
  integration_tests_backend:
    name: Backend API integration tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.build_branch }}

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        # The builtin cache feature ensures that installing golangci-lint
        # is consistently fast.
        cache: true
        cache-dependency-path: go.sum

    - name: Download go binary
      uses: actions/download-artifact@v4
      with:
        name: kiali
        path: ~/go/bin/

    - name: Ensure kiali binary is executable
      run: chmod +x ~/go/bin/kiali

    - name: Download frontend build
      uses: actions/download-artifact@v4
      with:
        name: build
        path: frontend/build

    - name: Run backend integration tests
      run: hack/run-integration-tests.sh --test-suite backend-external-controlplane $(if [ -n "${{ inputs.istio_version }}" ]; then echo "--istio-version ${{ inputs.istio_version }}"; fi)

    - name: Get debug info when integration tests fail
      if: failure()
      run: |
        mkdir debug-output
        hack/ci-get-debug-info.sh --output-directory debug-output --kubectl-context kind-controlplane

    - name: Upload debug info artifact
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: debug-info-${{ github.job }}
        path: debug-output
