name: Kiali CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
    - master
    - v*.*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  initialize:
    permissions:
      contents: read
    name: Initialize
    runs-on: ubuntu-latest
    outputs:
      target-branch: ${{ github.base_ref || github.ref_name }}
      build-branch: ${{ env.branch-master || env.branch-pr }}
    steps:
    - run: echo "target-branch -> ${{ github.base_ref || github.ref_name }}"
    - run: |
        echo "branch-version=${{ github.ref_name }}" >> $GITHUB_ENV
        echo "build-branch -> ${{ github.ref_name }}"
      id: branch-master
      if: ${{ !github.base_ref }}
    - run: |
        echo "branch-pr=refs/pull/${{ github.ref_name }}" >> $GITHUB_ENV
        echo "build-branch -> ${{ github.base_ref }}"
      id: branch-pr
      if: ${{ github.base_ref }}

  build_frontend:
    name: Build frontend
    uses: ./.github/workflows/build-frontend.yml
    needs: [initialize]
    with:
      target_branch: ${{ needs.initialize.outputs.target-branch }}
      build_branch: ${{ needs.initialize.outputs.build-branch }}

  build_backend:
    name: Build backend
    uses: ./.github/workflows/build-backend.yml
    needs: [initialize, build_frontend]
    with:
      build_branch: ${{ needs.initialize.outputs.build-branch }}

  integration_tests_frontend_ambient:
    name: Run Ambient frontend integration tests
    uses: ./.github/workflows/integration-tests-frontend-ambient.yml
    needs: [initialize, build_backend]
    with:
      target_branch: ${{ needs.initialize.outputs.target-branch }}
      build_branch: ${{ needs.initialize.outputs.build-branch }}
