name: Backend Unit Tests and Linters

on:
  workflow_call:
    inputs:
      build_branch:
        required: true
        type: string
jobs:
  build_backend:
    name: Run backend unit tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        ref: ${{ inputs.build_branch }}

    - name: Set up Go
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
      with:
        go-version-file: go.mod
        cache: true
        cache-dependency-path: go.sum

    - name: Lint Install
      run: make lint-install

    - name: Verify code formatting
      run: |
        make format
        if [[ $(git diff --stat) != '' ]]; then
          echo "Code is not properly formatted. Please run 'make format' and commit the changes."
          git diff
          exit 1
        fi

    - name: Verify code linting
      run: make lint

    - name: Run backend unit tests with coverage
      run: |
        make -e GO_TEST_FLAGS="-race -coverpkg=github.com/kiali/kiali/... -coverprofile=coverage-unit.out" test

    - name: Verify coverage profile
      run: wc -l coverage-unit.out

    - name: Upload unit coverage artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
      with:
        name: coverage-unit
        path: coverage-unit.out
