import * as React from 'react';
import { Divider, DropdownGroup, DropdownItem, Tooltip, TooltipPosition } from '@patternfly/react-core';
import { serverConfig } from 'config';
import { DestinationRule, getWizardUpdateLabel, K8sHTTPRoute, K8sGRPCRoute, VirtualService } from 'types/IstioObjects';
import { canDelete, ResourcePermissions } from 'types/Permissions';
import {
  SERVICE_WIZARD_ACTIONS,
  WIZARD_K8S_REQUEST_ROUTING,
  WIZARD_K8S_GRPC_REQUEST_ROUTING,
  WIZARD_TITLES,
  WizardAction,
  WizardMode,
  WIZARD_REQUEST_ROUTING,
  WIZARD_FAULT_INJECTION,
  WIZARD_TRAFFIC_SHIFTING,
  WIZARD_REQUEST_TIMEOUTS,
  WIZARD_TCP_TRAFFIC_SHIFTING
} from './WizardActions';
import { hasServiceDetailsTrafficRouting } from '../../types/ServiceInfo';
import { groupMenuStyle } from 'styles/DropdownStyles';
import { kialiStyle } from 'styles/StyleUtils';
import { t } from 'utils/I18nUtils';

export const DELETE_TRAFFIC_ROUTING = 'delete_traffic_routing';

type Props = {
  className?: string;
  destinationRules: DestinationRule[];
  isDisabled?: boolean;
  istioPermissions: ResourcePermissions;
  k8sGRPCRoutes: K8sGRPCRoute[];
  k8sHTTPRoutes: K8sHTTPRoute[];
  onAction?: (key: WizardAction, mode: WizardMode) => void;
  onDelete?: (key: string) => void;
  searchValue?: string;
  virtualServices: VirtualService[];
};

const optionDisabledStyle = kialiStyle({
  cursor: 'not-allowed',
  $nest: {
    '& button': {
      pointerEvents: 'none'
    }
  }
});

const dividerStyle = kialiStyle({
  paddingTop: '0.5rem'
});

const groupLabelStyle = kialiStyle({
  fontSize: '0.875rem',
  fontWeight: 700,
  color: 'var(--pf-v6-global--Color--200)',
  padding: '0.5rem 1rem',
  textTransform: 'uppercase',
  letterSpacing: '0.5px'
});

export const ServiceWizardActionsDropdownGroup: React.FunctionComponent<Props> = (props: Props) => {
  const updateLabel = getWizardUpdateLabel(props.virtualServices, props.k8sHTTPRoutes, props.k8sGRPCRoutes);
  const isViewOnly = serverConfig.deployment.viewOnlyMode;
  const searchLower = (props.searchValue || '').toLowerCase();

  const hasTrafficRouting = (): boolean => {
    return hasServiceDetailsTrafficRouting(
      props.virtualServices,
      props.destinationRules,
      props.k8sHTTPRoutes,
      props.k8sGRPCRoutes
    );
  };

  const handleActionClick = (eventKey: string): void => {
    if (props.onAction) {
      props.onAction(eventKey as WizardAction, updateLabel.length === 0 ? 'create' : 'update');
    }
  };

  const getDropdownItemTooltipMessage = (isGatewayAPI: boolean, hasExistingTrafficRouting: boolean): string => {
    if (isViewOnly && !hasExistingTrafficRouting) {
      return t('There is no traffic routing to view for this service');
    } else if (isViewOnly) {
      return t('No user permission or Kiali in view-only mode');
    } else if (hasExistingTrafficRouting) {
      return t('Traffic routing already exists for this service');
    } else if (isGatewayAPI) {
      return t('K8s Gateway API is not enabled');
    } else {
      return t("Traffic routing doesn't exists for this service");
    }
  };

  const actionItems = SERVICE_WIZARD_ACTIONS.filter(eventKey => {
    // Filter by search value
    const wizardTitle = t(WIZARD_TITLES[eventKey].title).toLowerCase();
    return wizardTitle.includes(searchLower);
  }).map(eventKey => {
    const isGatewayAPIEnabled =
      eventKey === WIZARD_K8S_REQUEST_ROUTING || eventKey === WIZARD_K8S_GRPC_REQUEST_ROUTING
        ? serverConfig.gatewayAPIEnabled
        : true;
    const hasExistingTrafficRouting = hasTrafficRouting();

    const istioWizardKeys = [
      WIZARD_REQUEST_ROUTING,
      WIZARD_FAULT_INJECTION,
      WIZARD_TRAFFIC_SHIFTING,
      WIZARD_REQUEST_TIMEOUTS,
      WIZARD_TCP_TRAFFIC_SHIFTING
    ];

    const isIstioAPIInstalled = istioWizardKeys.includes(eventKey) ? serverConfig.istioAPIInstalled : true;

    const enabledItem =
      isGatewayAPIEnabled &&
      isIstioAPIInstalled &&
      !props.isDisabled &&
      (isViewOnly
        ? hasExistingTrafficRouting && updateLabel === eventKey
        : !hasExistingTrafficRouting || updateLabel === eventKey);

    const wizardItem = (
      <DropdownItem
        className={props.className}
        key={eventKey}
        component="button"
        isDisabled={!enabledItem}
        onClick={() => handleActionClick(eventKey)}
        data-test={eventKey}
      >
        {t(WIZARD_TITLES[eventKey].title)}
      </DropdownItem>
    );

    // An Item is rendered under two conditions:
    // a) No traffic -> Wizard can create new one
    // b) Existing traffic generated by the traffic -> Wizard can update that scenario
    // Otherwise, the item should be disabled
    if (!enabledItem) {
      return (
        <Tooltip
          key={`tooltip_${eventKey}`}
          position={TooltipPosition.left}
          content={<>{getDropdownItemTooltipMessage(!isGatewayAPIEnabled, hasExistingTrafficRouting)}</>}
        >
          <div className={optionDisabledStyle}>{wizardItem}</div>
        </Tooltip>
      );
    } else {
      return wizardItem;
    }
  });

  // Only show delete action if it matches search filter
  const deleteText = t('Delete Traffic Routing').toLowerCase();
  const shouldShowDelete = deleteText.includes(searchLower);

  if (shouldShowDelete) {
    actionItems.push(<Divider className={dividerStyle} key="actions_separator" />);

    const deleteDisabled = !canDelete(props.istioPermissions) || !hasTrafficRouting() || props.isDisabled;

    let deleteDropdownItem = (
      <DropdownItem
        key={DELETE_TRAFFIC_ROUTING}
        component="button"
        onClick={() => {
          if (props.onDelete) {
            props.onDelete(DELETE_TRAFFIC_ROUTING);
          }
        }}
        isDisabled={deleteDisabled}
        data-test={DELETE_TRAFFIC_ROUTING}
      >
        {t('Delete Traffic Routing')}
      </DropdownItem>
    );

    if (deleteDisabled) {
      deleteDropdownItem = (
        <Tooltip
          key={`tooltip_${DELETE_TRAFFIC_ROUTING}`}
          position={TooltipPosition.left}
          content={<>{getDropdownItemTooltipMessage(false, hasTrafficRouting())}</>}
        >
          <div style={{ display: 'inline-block', cursor: 'not-allowed' }}>{deleteDropdownItem}</div>
        </Tooltip>
      );
    }

    actionItems.push(deleteDropdownItem);
  }
  const label = isViewOnly ? t('View') : updateLabel === '' ? t('Create') : t('Update');

  // Don't render the group if no items match the search
  if (actionItems.length === 0) {
    return null;
  }

  return (
    <>
      <div className={groupLabelStyle}>{label}</div>
      <DropdownGroup key={`group_${label}`} className={groupMenuStyle} children={actionItems} />
    </>
  );
};
